### ISSUE TITLE
Inappropriate "foo" usage in form_for

### ISSUE THREAD

**Issue by joshprice** [ash-project/ash_phoenix#48]
Potentially strange usages of "foo" in form_for:

https://github.com/ash-project/ash_phoenix/blob/09f673751b0c5822fe97fc1a08a80382a3250b3a/lib/ash_phoenix/form/form.ex#L1335

https://github.com/ash-project/ash_phoenix/blob/09f673751b0c5822fe97fc1a08a80382a3250b3a/lib/ash_phoenix/form/form.ex#L1502

Not necessarily a bug but may need clarification

**Comment by zachdaniel** [comment]
Yeah, it is done in cases where the `form_for` call does some logic we don't want to repeat, but it was a pretty lazy way to do it since converting to a form does *other* things. I've moved the logic out to a shared place for the case of hidden fields, and just duplicated the logic there for showing errors. Thanks for pointing it out :)
